name: Flutter Analyze

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  analyze:
    name: Analyze with Dart
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 💾 Install Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: 📦 Install dependencies
        run: flutter pub get

      - name: 🧪 Run Dart Analyzer
        run: dart analyze
